package com.ethanaa.deepcrawl.writer.entity;


import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.ethanaa.deepcrawl.writer.entity.converter.LocalDateTimeConverter;
import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;

import java.time.LocalDateTime;

import static com.ethanaa.deepcrawl.writer.entity.SearchTerm.TABLE_NAME;

@DynamoDBTable(tableName = TABLE_NAME)
public class SearchTerm {

    public static final String TABLE_NAME = "SearchTerm";

    @DynamoDBHashKey(attributeName = "Uuid")
    @DynamoDBAutoGeneratedKey
    private String uuid;

    @DynamoDBAttribute(attributeName = "ApiKey")
    private String apiKey = "";

    @DynamoDBAttribute(attributeName = "Regex")
    private String regex = "";

    @DynamoDBIndexRangeKey(attributeName = "NumHits")
    private Long numHits = 0L;

    @DynamoDBIndexRangeKey(attributeName = "CreatedAt")
    @DynamoDBMarshalling(marshallerClass = LocalDateTimeConverter.class)
    private LocalDateTime createdAt = LocalDateTime.now();

    @DynamoDBIndexRangeKey(attributeName = "UpdatedAt")
    @DynamoDBMarshalling(marshallerClass = LocalDateTimeConverter.class)
    private LocalDateTime updatedAt = LocalDateTime.now();

    public SearchTerm(String apiKey, String regex) {

        this.apiKey = apiKey;
        this.regex = regex;
    }

    public SearchTerm() {
        //
    }

    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public String getApiKey() {
        return apiKey;
    }

    public void setApiKey(String apiKey) {
        this.apiKey = apiKey;
    }

    public String getRegex() {
        return regex;
    }

    public void setRegex(String regex) {
        this.regex = regex;
    }

    public Long getNumHits() {
        return numHits;
    }

    public void setNumHits(Long numHits) {
        this.numHits = numHits;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        SearchTerm that = (SearchTerm) o;
        return Objects.equal(uuid, that.uuid);
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(uuid);
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
                .add("uuid", uuid)
                .add("apiKey", apiKey)
                .add("regex", regex)
                .add("numHits", numHits)
                .add("createdAt", createdAt)
                .add("updatedAt", updatedAt)
                .toString();
    }
}
